### ISSUE TITLE
missing overlay.png

### ISSUE THREAD

**Issue by brendonjohn** [gregplaysguitar/djangocms2000#18]
[static/cms/css/login.css on line 9](https://github.com/gregplaysguitar/djangocms2000/blob/dev/cms/static/cms/css/login.css), links to an image that isn't available in the project.

> "ValueError: The file 'cms/images/overlay.png' could not be found"

**Comment by gregplaysguitar** [comment]
Hmm, weird - that file isn't even in use. Thanks
